#cloud-config
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - wget
  - gnupg-agent
  - software-properties-common
  - git
runcmd:
  - cd /opt
  - git clone https://github.com/hiddify/hiddify-config/
  - cd hiddify-config
  - echo "USER_SECRET=44da16ea20ff4bac92afae43ef97f067" >config.env
  - echo "MAIN_DOMAIN=example.com" >>config.env
  - bash install.sh

power_state:
  mode: reboot
  message: please open https://example.com/44da16ea20ff4bac92afae43ef97f067