# Please don't modify this file
# Please don't modify this file
# Please don't modify this file
# modify only config.env file. you can override the variables here in config.env 

global:
  # list of ports for tls entry point
  tls_ports: 
    - 443

  # list of ports for http entry point (port 80 is mandatory)
  http_ports: 
    - 80

  # can be a string with any lenght (automatically generate if not present)
  base_proxy_path:

  # allow only tls ports and http ports in firewall
  firewall: true

  # resource monitoring
  netdata: true

  # allow unencrypted proxy
  http_proxy: true

  # iran_sites can be block, proxy, cfwrap, cfwrap means cloud flare wrap
  iran_sites: proxy

  # if the request is other domains
  allow_invalid_sni: true

  auto_update: true

  speed_test: true

  # disable ipv6
  only_ipv4: true


admin_secret: 

# list of users in the system
users:
  - name: "hiddify"

    # uuid is 32 char
    uuid: "0123456789ABCDEF0123456789ABCDEF"

    # bandwidth is a float in GB. 0 means unlimited
    monthly_usage_limit: 10

    # used bandwidth this month
    current_usage: 0

    # expire time (monthly bandwith will be reset every 30 days before expiry time)
    expiry_time: "2023/02/10"




domains:
   - test.hiddify.com:
        cdn: true


services:
  telegram:
    enable: true

    # 32 char uuid common between all your users
    secret: 

    # demonestrate fake_tls_domain for preventing probing
    fake_tls_domain: mail.google.com

    #adtag not supported now
    # ad_tag:  

  ss_faketls:
    enable: true

    # 32 char uuid common between all your users
    secret: 
    
    # demonestrate fake_tls_domain for preventing probing
    fake_tls_domain: www.google.com
    

github:
   user: hiddify
   repository: hiddify-config
   branch_or_tag: main

