#cloud-config
groups:
  - gost
users:
  - default
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - wget
  - gnupg-agent
  - software-properties-common
  - git
runcmd:
  - mkdir -p /opt/gost; cd /opt/gost
  - wget https://github.com/ginuerzh/gost/releases/download/v2.11.4/gost-linux-amd64-2.11.4.gz
  - gunzip gost*
  - mv gost* gost
  - chmod +x gost
  - wget https://raw.githubusercontent.com/hiddify/config/main/gost-systemd.service -O gost.service
  - sudo systemctl enable gost.service
  - sudo systemctl start gost.service
power_state:
  mode: reboot
  message: Restarting after installing docker & docker-compose
