#cloud-config
groups:
  - docker
users:
  - default
  # the docker service account
  - name: docker-service
    groups: docker
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - git
runcmd:
  # install docker following the guide: https://docs.docker.com/install/linux/docker-ce/ubuntu/
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get -y update
  - sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-compose
  - sudo systemctl enable docker
  - cd /opt/
  - git clone https://github.com/alexbers/mtprotoproxy 
  - cd  mtprotoproxy
  - sed -i 's/00000000000000000000000000000001/751F2F753854422EA4C5FDDB8314F068/g' config.py
  - echo 'TLS_DOMAIN = "www.googleapis.com"'>> config.py
  - docker-compose up -d
power_state:
  mode: reboot
  message: Restarting after installing docker & docker-compose
